---
apiVersion: apps/v1
kind: Deployment
namespace: demo-project
metadata:
  name: springboot-demo
  labels:
    app: springboot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot
          image: image-registry.openshift-image-registry.svc:5000/demo-project/springboot-demo:latest
          ports:
            - containerPort: 8070
---
apiVersion: v1
kind: Service
namespace: demo-project
metadata:
  name: springboot-service
  labels:
    app: springboot-demo
spec:
  selector:
    app: springboot-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
---
apiVersion: route.openshift.io/v1
kind: Route
namespace: demo-project
metadata:
  name: springboot-route
  labels:
    app: springboot-demo
spec:
  to:
    kind: Service
    name: springboot-service
  port:
    targetPort: 8070
